# Generated by Django 4.1.6 on 2023-02-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estimated_target', models.IntegerField(default='')),
                ('Achieved_target', models.IntegerField(default='')),
                ('Score', models.IntegerField(default='')),
                ('Bonus', models.IntegerField(default='')),
                ('Datetime', models.DateField(default='')),
                ('Time', models.TimeField(default='')),
            ],
        ),
    ]
