# Generated by Django 4.1.7 on 2023-02-17 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estimated_target', models.IntegerField(default='')),
                ('Achieved_target', models.IntegerField(default='')),
                ('Score', models.IntegerField(default='')),
                ('Bonus', models.IntegerField(default='')),
                ('Datetime', models.DateField(default='')),
                ('Time', models.TimeField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
