# Generated by Django 4.1.7 on 2023-02-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_process_processalert_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('weights_path', models.FileField(upload_to='')),
                ('config_path', models.FileField(upload_to='')),
                ('xml_path', models.FileField(upload_to='')),
            ],
        ),
    ]
